spring:
  application:
    name: "kongju"
  profiles:
    active: kakao, aws
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    tags-sorter: method
    operations-sorter: alpha
    groups-order: desc

frontend:
  domain: "http://localhost:3000"
