spring:
  application:
    name: "kongju"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    tags-sorter: method
    operations-sorter: alpha
    groups-order: desc

server:
  servlet:
    session:
      cookie:
        secure: true # HTTPS 사용 시 true
        http-only: true
        same-site: none # 다른 도메인 간 쿠키 전송 허용
