spring:
  application:
    name: "kongju"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    tags-sorter: method
    operations-sorter: alpha
    groups-order: desc

server:
  servlet:
    session:
      cookie:
        secure: true # HTTPS 사용 시 true
        http-only: true
        same-site: none # 다른 도메인 간 쿠키 전송 허용

cloud:
  aws:
    s3:
      bucket: mock-bucket-name
    credentials:
      access-key: mock-access-key
      secret-key: mock-secret-key
    region:
      static: "ap-northeast-2"
      auto: false
    stack:
      auto: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true