cloud:
  aws:
    s3:
      bucket: "kongju-s3-bucket"
    credentials:
      access-key: "AKIAX3DNHW74CKSK2DMG"
      secret-key: "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"
    region:
      static: "ap-northeast-2"
      auto: false
    stack:
      auto: false