spring:
  config:
    activate:
      on-profile: local
    import:
        - classpath:secrets/application-common.yml
        - classpath:secrets/application-local.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
        - classpath:secrets/application-common.yml
        - classpath:secrets/application-prod.yml